version: '3.10'

services:
        to-do-manager:
                volumes:
                - /home/ubuntu/todo.db:/usr/app/instance/todo.db
                - /home/ubuntu/.env:/usr/app/backend/.env
                image: mattmcauley/to-do-manager
                env_file: .env
                ports:
                - "80:8000"